    // File: src/data.js
    export const products = [
        { id: 1, name: "Laptop", price: 100000, image: "/01.jpg", description: "A powerful laptop." },
        { id: 2, name: "Smartphone", price: 500, image: "/02.jpg", description: "A sleek smartphone." },
        { id: 3, name: "Headphones", price: 200, image:"/03.webp", description: "Noise-cancelling headphones." },
        { id: 4, name: "Tablet", price: 350, image:"/04.jpg", description: "A lightweight tablet." },
        { id: 5, name: "Smartwatch", price: 150, image:"/05.jpg", description: "A fitness tracking smartwatch." },
        { id: 6, name: "Monitor", price: 300, image:"/06.avif", description: "A 24-inch Full HD monitor." },
        { id: 7, name: "Keyboard", price: 50, image:"/07.webp", description: "A mechanical keyboard." },
        { id: 8, name: "Mouse", price: 30, image:"/08.jpg", description: "A wireless mouse." },
        { id: 9, name: "Speakers", price: 120, image:"/09.jpg", description: "High-quality stereo speakers." },
        { id: 10, name: "Camera", price: 600, image:"/10.jpg", description: "A DSLR camera." },
        { id: 11, name: "Printer", price: 180, image:"/11.jpg", description: "A color inkjet printer." },
        { id: 12, name: "Charger", price: 25, image:"/12.jpg", description: "A fast charging USB charger." },
        { id: 13, name: "External Hard Drive", price: 80, image:"/13.jpg", description: "A 1TB external hard drive." },
        { id: 14, name: "TV", price: 700, image:"/14.jpg", description: "A 55-inch 4K UHD TV." },
        { id: 15, name: "Bluetooth Speaker", price: 60, image:"/15.jpg", description: "Portable Bluetooth speaker." },
        { id: 16, name: "Camera Lens", price: 250, image:"/16.jpg", description: "A 50mm camera lens." },
        { id: 17, name: "Projector", price: 500, image:"/17.jpg", description: "A mini projector for home theater." },
        { id: 18, name: "Guitar", price: 200, image:"/18.jpg", description: "A classical acoustic guitar." },
        { id: 19, name: "Drone", price: 450, image:"/19.jpg", description: "A high-definition drone." },
        { id: 20, name: "Coffee Machine", price: 100, image:"/20.jpg", description: "A smart coffee machine." },
        { id: 21, name: "Electric Kettle", price: 40, image:"/21.jpg", description: "An electric kettle with quick boil feature." },
        { id: 22, name: "Action Camera", price: 120, image:"/22.jpg", description: "Waterproof action camera." },
        { id: 23, name: "VR Headset", price: 350, image:"/23.jpg", description: "Virtual Reality headset." },
        { id: 24, name: "Car Charger", price: 20, image:"/24.jpg", description: "A dual-port car charger." },
        { id: 25, name: "Electric Skateboard", price: 500, image:"/25.jpg", description: "A fast electric skateboard." },
        { id: 26, name: "Smart Light Bulbs", price: 40, image:"/26.jpg", description: "Smart LED light bulbs." },
        { id: 27, name: "Washing Machine", price: 350, image:"/27.jpg", description: "A top-loading washing machine." },
        { id: 28, name: "Rice Cooker", price: 50, image:"/28.jpg", description: "A digital rice cooker." },
        { id: 29, name: "Electric Fan", price: 30, image:"/29.jpg", description: "A quiet electric fan." },
        { id: 30, name: "Air Purifier", price: 150, image:"/30.jpg", description: "An air purifier for home." }
    ];
    